
##########
# Below defines the various HTTP routes supported by the system 
# and which controller within the /src/HttpControllers/ directory handles them.
#
# Please refer to the documentation for full details.
##########

routes:
    api: RestApi
    default: PublicSite


